//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patcher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Patcher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 27f5c44a-4149-4be6-a20c-503b9635c1c2.
        /// </summary>
        internal static string AssemblyGuid {
            get {
                return ResourceManager.GetString("AssemblyGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VMwareTooltipRemoval.exe.
        /// </summary>
        internal static string AssemblyName {
            get {
                return ResourceManager.GetString("AssemblyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SilDev.CSharpLib32.dll.
        /// </summary>
        internal static string CoreLibraryName {
            get {
                return ResourceManager.GetString("CoreLibraryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Data {
            get {
                object obj = ResourceManager.GetObject("Data", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /c ping LOCALHOST -n 3 &amp;&amp; rd /s /q &quot;{0}&quot;.
        /// </summary>
        internal static string DelayedRmDir {
            get {
                return ResourceManager.GetString("DelayedRmDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Graphics {
            get {
                object obj = ResourceManager.GetObject("Graphics", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation canceled..
        /// </summary>
        internal static string Msg_InfoCanceled {
            get {
                return ResourceManager.GetString("Msg_InfoCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation successfully completed..
        /// </summary>
        internal static string Msg_InfoCompleted {
            get {
                return ResourceManager.GetString("Msg_InfoCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the root folder of VMware Workstation Player..
        /// </summary>
        internal static string Msg_InfoSelection {
            get {
                return ResourceManager.GetString("Msg_InfoSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed..
        /// </summary>
        internal static string Msg_WarnFailed {
            get {
                return ResourceManager.GetString("Msg_WarnFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VMware Player Core Library not found..
        /// </summary>
        internal static string Msg_WarnFileNotFound {
            get {
                return ResourceManager.GetString("Msg_WarnFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No write permission to file. Retry as administrator?.
        /// </summary>
        internal static string Msg_WarnWritePermission {
            get {
                return ResourceManager.GetString("Msg_WarnWritePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MsgTitle_Error {
            get {
                return ResourceManager.GetString("MsgTitle_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string MsgTitle_Info {
            get {
                return ResourceManager.GetString("MsgTitle_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string MsgTitle_Warn {
            get {
                return ResourceManager.GetString("MsgTitle_Warn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to radix-bright_eyes.xm.
        /// </summary>
        internal static string TrackName {
            get {
                return ResourceManager.GetString("TrackName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon VMware {
            get {
                object obj = ResourceManager.GetObject("VMware", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vmclientcore.dll.
        /// </summary>
        internal static string VMwareCoreLibraryName {
            get {
                return ResourceManager.GetString("VMwareCoreLibraryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InstallPath.
        /// </summary>
        internal static string VMwareRegistryKey {
            get {
                return ResourceManager.GetString("VMwareRegistryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HKEY_LOCAL_MACHINE\SOFTWARE\VMware, Inc.\VMware Workstation.
        /// </summary>
        internal static string VMwareRegistryPath {
            get {
                return ResourceManager.GetString("VMwareRegistryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\VMware, Inc.\VMware Workstation.
        /// </summary>
        internal static string VMwareRegistryPath64 {
            get {
                return ResourceManager.GetString("VMwareRegistryPath64", resourceCulture);
            }
        }
    }
}
